fix: ios and android builds
ACE-IoT-Solutions/connecting-mha-app pull request #9
Opened 2024-02-15 00:55 UTC by vickiwong85

# Problem
ios and android builds were failing due to old dependencies 

# Solution:
update dependencies and fix any resulting errors

android:
- update gradle from 7.3.3 to 7.5.1
- upgrade AGP dependency from 7.3.1 to 7.4.2 
- move package from android manifest and apply plugin: "com.facebook.react" to build.gradle
- add hermesEnabled: false to gradle-wrapper.properties

ios:
- update ios deployment target from 12.4 to 13.0
- update expo to 48.0.0
- pass in true boolean to second argument for RCTAppSetupPrepareApp()

API update:
- update default endpoint

https://github.com/ACE-IoT-Solutions/connecting-mha-app/assets/94999450/e7b9cccb-16d6-41d3-8796-c9608b61cdbb

2024-02-16 20:10 UTC, mia-lorraine commented
i suggest squashing all commits before merge c:

2024-02-16 21:53 UTC, mia-lorraine commented on yarn.lock
> +expo-updates@~0.16.4:
[expo-updates](https://github.com/ACE-IoT-Solutions/connecting-mha-app/pull/5) addressed here

2024-02-16 21:54 UTC, mia-lorraine commented on yarn.lock
> +"@react-navigation/native@^6.1.7":
[react-navigation/native](https://github.com/ACE-IoT-Solutions/connecting-mha-app/pull/4) addressed

2024-02-16 21:57 UTC, mia-lorraine commented on yarn.lock
> +react-dom@18.2.0:
[PR addressed](https://github.com/ACE-IoT-Solutions/connecting-mha-app/pull/1)

2024-02-16 21:59 UTC, mia-lorraine commented on yarn.lock
> +"@expo/cli@0.7.3":
[expo cli update](https://github.com/ACE-IoT-Solutions/connecting-mha-app/pull/6) to 0.7.3

2024-02-20 00:18 UTC, vickiwong85 commented on package.json
> +    "@react-navigation/bottom-tabs": "^6.5.7",
[bottom-tabs update](#3) addressed here

2024-02-20 00:22 UTC, vickiwong85 commented on package.json
> +    "@react-navigation/native-stack": "^6.9.12",
[native stack upgrade](#2 ) addressed here

2024-02-20 20:35 UTC, mia-lorraine requested changes
imo, would make a new PR to show files changed and squash commits for a cleaner merge c:

2024-02-20 21:31 UTC, closed without merging